import { defineType, defineField } from "sanity";
import { FontPreview } from "../../components/FontPreview";

export default defineType({
  name: "siteSettings",
  title: "Site Settings",
  type: "document",
  icon: () => "⚙️",
  // Field groups create tabs — keeps the settings panel clean instead of one long scroll
  groups: [
    { name: "identity", title: "👤  Identity", default: true },
    { name: "navigation", title: "🔗  Navigation" },
    { name: "theme", title: "🎨  Theme & Colours" },
    { name: "typography", title: "✏️  Typography" },
    { name: "footer", title: "📄  Footer" },
  ],
  fields: [
    // ── Identity ──────────────────────────────────────────────────
    defineField({
      name: "siteName",
      title: "Your Name",
      type: "string",
      group: "identity",
      initialValue: "Noa Plinke",
      description: "Used as the site title and in search results.",
      validation: (Rule) => Rule.required().error("Please enter your name."),
    }),
    defineField({
      name: "tagline",
      title: "Tagline",
      type: "string",
      group: "identity",
      initialValue: "Animation that hits different",
      description: "A short phrase that describes you — shown in browser tab titles.",
    }),
    defineField({
      name: "siteDescription",
      title: "Site Description",
      type: "text",
      rows: 3,
      group: "identity",
      initialValue: "Portfolio of Noa Plinke, a 3D Gameplay Animator specializing in combat systems, procedural motion, and game development.",
      description: "The description shown in Google search results, link previews (WhatsApp, Messenger, LinkedIn, Discord etc.), and browser tooltips. Keep it to 1–2 sentences, ideally under 160 characters.",
      validation: (Rule) => Rule.max(300).warning("Over 160 characters may get cut off in search results."),
    }),
    defineField({
      name: "email",
      title: "Contact Email",
      type: "string",
      group: "identity",
      description: "Used in the contact button and footer. e.g., hello@noaplinke.com.",
      validation: (Rule) => Rule.required().error("Please add your email address."),
    }),
    defineField({
      name: "logo",
      title: "Logo Image",
      type: "image",
      group: "identity",
      description: "Optional. If left empty, your name is shown as text in the navbar.",
      options: { hotspot: true },
    }),
    defineField({
      name: "ogImage",
      title: "Social Share Image (OG Image)",
      type: "image",
      group: "identity",
      description: "The image shown when someone shares your site on LinkedIn, Twitter, Discord, etc. Ideal size: 1200×630px. If left empty, an auto-generated branded image is used.",
      options: { hotspot: true },
      fields: [
        { name: "alt", title: "Alt Text", type: "string", description: "Describe the image." },
      ],
    }),
    defineField({
      name: "socialLinks",
      title: "Social Links",
      type: "array",
      group: "identity",
      description: "Your social media profiles. Shown in the footer.",
      of: [
        {
          type: "object",
          fields: [
            {
              name: "platform",
              title: "Platform",
              type: "string",
              options: {
                list: [
                  { title: "LinkedIn", value: "linkedin" },
                  { title: "ArtStation", value: "artstation" },
                  { title: "YouTube", value: "youtube" },
                  { title: "Twitter / X", value: "twitter" },
                  { title: "itch.io", value: "itchio" },
                  { title: "GitHub", value: "github" },
                  { title: "Instagram", value: "instagram" },
                  { title: "Vimeo", value: "vimeo" },
                ],
              },
            },
            { name: "url", title: "Profile URL", type: "url" },
          ],
          preview: {
            select: { title: "platform", subtitle: "url" },
          },
        },
      ],
    }),

    // ── Navigation ────────────────────────────────────────────────
    defineField({
      name: "navLinks",
      title: "Navigation Links",
      type: "array",
      group: "navigation",
      description: "The links shown in the top navigation bar. Drag to reorder.",
      of: [
        {
          type: "object",
          fields: [
            { name: "label", title: "Label", type: "string", description: "The text shown in the nav, e.g., 'Portfolio'." },
            { name: "href", title: "Link", type: "string", description: "e.g., #portfolio (same-page anchor) or /about (separate page)." },
          ],
          preview: {
            select: { title: "label", subtitle: "href" },
          },
        },
      ],
    }),
    defineField({
      name: "projectCategories",
      title: "Portfolio Filter Categories",
      type: "array",
      group: "navigation",
      of: [{ type: "string" }],
      description: "The filter options shown above the portfolio grid. Add or remove categories here.",
      initialValue: ["Procedural Animation", "Keyframe Animation", "Motion Capture"],
    }),

    // ── Theme & Colours ───────────────────────────────────────────
    defineField({
      name: "theme",
      title: "Colour Palette",
      type: "object",
      group: "theme",
      description: "Changes the colour scheme across the entire site. The defaults are dark/lime/purple.",
      fields: [
        {
          name: "bgDark",
          title: "Dark Background",
          type: "color",
          description: "Used for the hero, footer, and dark sections. Default: #0e0e10.",
        },
        {
          name: "bgLight",
          title: "Light Background",
          type: "color",
          description: "Used for portfolio, games, and about sections. Default: #f8f8f6.",
        },
        {
          name: "accent",
          title: "Primary Accent",
          type: "color",
          description: "The main highlight colour — buttons, tags, hover states. Default: #c9fb00 (lime).",
        },
        {
          name: "accentSecondary",
          title: "Secondary Accent",
          type: "color",
          description: "Used for category labels, links, and decorative details. Default: #7b61ff (purple).",
        },
      ],
    }),

    // ── Typography ────────────────────────────────────────────────
    defineField({
      name: "fontPreview",
      title: "Preview",
      type: "string",
      group: "typography",
      readOnly: true,
      hidden: false,
      components: { input: FontPreview as any },
    }),
    defineField({
      name: "displayFont",
      title: "Display Font",
      type: "object",
      group: "typography",
      description: "Used for all headings, section titles, the logo, and large display text.",
      options: { collapsible: false },
      fields: [
        defineField({
          name: "family",
          title: "Font Family",
          type: "string",
          initialValue: "Syne",
          options: {
            list: [
          { title: "Syne (Default)", value: "Syne" },
          { title: "Space Grotesk", value: "Space Grotesk" },
          { title: "Outfit", value: "Outfit" },
          { title: "Plus Jakarta Sans", value: "Plus Jakarta Sans" },
          { title: "Unbounded", value: "Unbounded" },
          { title: "Oswald", value: "Oswald" },
          { title: "Raleway", value: "Raleway" },
          { title: "Barlow Condensed", value: "Barlow Condensed" },
          { title: "Bebas Neue", value: "Bebas Neue" },
          { title: "Anton", value: "Anton" },
          { title: "Archivo Black", value: "Archivo Black" },
          { title: "DM Serif Display", value: "DM Serif Display" },
          { title: "Playfair Display", value: "Playfair Display" },
          { title: "Cormorant Garamond", value: "Cormorant Garamond" },
          { title: "Fraunces", value: "Fraunces" },
          { title: "Inter", value: "Inter" },
          { title: "Manrope", value: "Manrope" },
          { title: "━━━━━━━━━━━━━━━━━━━━━━━━━", value: "__sep__" },
          { title: "↑ Upload Custom Font ↑", value: "__custom__" },
        ],
            layout: "dropdown",
          },
          description: "Choose from curated Google Fonts, or select \"Upload Custom Font\" to use your own.",
        }),
        defineField({
          name: "customFile",
          title: "Custom Font File",
          type: "file",
          description: "Upload a .woff2, .woff, .ttf, or .otf file.",
          options: { accept: ".woff2,.woff,.ttf,.otf" },
          hidden: ({ parent }: any) => parent?.family !== "__custom__",
        }),
        defineField({
          name: "customName",
          title: "Custom Font Name",
          type: "string",
          description: "The name you want to use — e.g. \"MyBrandFont\". This becomes the font-family name on the site.",
          hidden: ({ parent }: any) => parent?.family !== "__custom__",
        }),
        defineField({
          name: "weight",
          title: "Font Weight",
          type: "string",
          initialValue: "700",
          options: {
            list: [
          { title: "100 — Thin", value: "100" },
          { title: "200 — Extra Light", value: "200" },
          { title: "300 — Light", value: "300" },
          { title: "400 — Regular", value: "400" },
          { title: "500 — Medium", value: "500" },
          { title: "600 — Semi Bold", value: "600" },
          { title: "700 — Bold", value: "700" },
          { title: "800 — Extra Bold", value: "800" },
          { title: "900 — Black", value: "900" },
        ],
            layout: "dropdown",
          },
          description: "Not all fonts support every weight — the font will use its nearest available weight.",
        }),
      ],
    }),
    defineField({
      name: "bodyFont",
      title: "Body Font",
      type: "object",
      group: "typography",
      description: "Used for all paragraph text, descriptions, UI labels, and general copy.",
      options: { collapsible: false },
      fields: [
        defineField({
          name: "family",
          title: "Font Family",
          type: "string",
          initialValue: "DM Sans",
          options: {
            list: [
          { title: "DM Sans (Default)", value: "DM Sans" },
          { title: "Inter", value: "Inter" },
          { title: "Plus Jakarta Sans", value: "Plus Jakarta Sans" },
          { title: "Poppins", value: "Poppins" },
          { title: "Nunito Sans", value: "Nunito Sans" },
          { title: "Manrope", value: "Manrope" },
          { title: "Work Sans", value: "Work Sans" },
          { title: "Outfit", value: "Outfit" },
          { title: "Karla", value: "Karla" },
          { title: "Mulish", value: "Mulish" },
          { title: "Lato", value: "Lato" },
          { title: "Source Sans 3", value: "Source Sans 3" },
          { title: "Syne", value: "Syne" },
          { title: "━━━━━━━━━━━━━━━━━━━━━━━━━", value: "__sep__" },
          { title: "↑ Upload Custom Font ↑", value: "__custom__" },
        ],
            layout: "dropdown",
          },
          description: "Choose from curated Google Fonts, or select \"Upload Custom Font\" to use your own.",
        }),
        defineField({
          name: "customFile",
          title: "Custom Font File",
          type: "file",
          description: "Upload a .woff2, .woff, .ttf, or .otf file.",
          options: { accept: ".woff2,.woff,.ttf,.otf" },
          hidden: ({ parent }: any) => parent?.family !== "__custom__",
        }),
        defineField({
          name: "customName",
          title: "Custom Font Name",
          type: "string",
          description: "The name you want to use — e.g. \"MyBrandFont\". This becomes the font-family name on the site.",
          hidden: ({ parent }: any) => parent?.family !== "__custom__",
        }),
        defineField({
          name: "weight",
          title: "Font Weight",
          type: "string",
          initialValue: "400",
          options: {
            list: [
          { title: "100 — Thin", value: "100" },
          { title: "200 — Extra Light", value: "200" },
          { title: "300 — Light", value: "300" },
          { title: "400 — Regular", value: "400" },
          { title: "500 — Medium", value: "500" },
          { title: "600 — Semi Bold", value: "600" },
          { title: "700 — Bold", value: "700" },
          { title: "800 — Extra Bold", value: "800" },
          { title: "900 — Black", value: "900" },
        ],
            layout: "dropdown",
          },
          description: "400 (Regular) recommended for body text.",
        }),
      ],
    }),

    // ── Footer ────────────────────────────────────────────────────
    defineField({
      name: "footerText",
      title: "Footer Heading",
      type: "string",
      group: "footer",
      initialValue: "Let's make something awesome",
      description: "The big heading shown above your email in the footer.",
    }),
    defineField({
      name: "copyright",
      title: "Copyright Text",
      type: "string",
      group: "footer",
      initialValue: "© 2025 Noa Plinke",
      description: "Shown at the very bottom of the site.",
    }),
  ],
  preview: {
    prepare() {
      return { title: "Site Settings" };
    },
  },
});
