import { defineType, defineField } from "sanity";

export default defineType({
  name: "heroBanner",
  title: "Hero Banner",
  type: "object",
  icon: () => "🎬",
  fieldsets: [
    {
      name: "content",
      title: "✏️  Text Content",
      description: "The heading, subtitle, and tags that appear on the left side of the hero.",
      options: { collapsible: true, collapsed: false },
    },
    {
      name: "visual",
      title: "🖼️  Hero Visual",
      description: "What appears on the right side — choose image, video, or your 3D character.",
      options: { collapsible: true, collapsed: false },
    },
    {
      name: "background",
      title: "🎨  Background & Particles",
      description: "Colour scheme and decorative particles behind the hero content.",
      options: { collapsible: true, collapsed: true },
    },
    {
      name: "cta",
      title: "🔗  Call to Action",
      description: "The button that links to your email or a URL.",
      options: { collapsible: true, collapsed: true },
    },
  ],
  fields: [
    // ── Text Content ─────────────────────────────────────────────
    defineField({
      name: "heading",
      title: "Heading",
      type: "string",
      fieldset: "content",
      initialValue: "Animation that hits different",
      validation: (Rule) => Rule.required().error("Please add a heading for your hero section"),
    }),
    defineField({
      name: "subtitle",
      title: "Subtitle",
      type: "text",
      rows: 3,
      fieldset: "content",
      description: "A short sentence or two below the heading.",
    }),
    defineField({
      name: "tags",
      title: "Specialty Tags",
      type: "array",
      of: [{ type: "string" }],
      fieldset: "content",
      description: "The scattered pill tags that float around the hero (e.g., Gameplay Animation, Rigging).",
      initialValue: [
        "Gameplay Animation",
        "Game Development",
        "Engine Implementation",
        "Workflow Optimization",
        "Rigging",
        "Procedural Animations",
      ],
    }),

    // ── Hero Visual ───────────────────────────────────────────────
    defineField({
      name: "heroDisplay",
      title: "What to show on the right",
      type: "string",
      fieldset: "visual",
      description: "Pick one: a static image, a looping video, or your interactive 3D character.",
      options: {
        list: [
          { title: "🖼  Image", value: "image" },
          { title: "🎬  Video (looping)", value: "video" },
          { title: "🤖  3D Character (interactive, cursor-tracked)", value: "3d" },
        ],
        layout: "radio",
      },
      initialValue: "image",
    }),
    defineField({
      name: "heroImage",
      title: "Hero Image",
      type: "image",
      fieldset: "visual",
      options: { hotspot: true },
      description: "Shown when 'Image' is selected above. Use the hotspot tool to set the focal point.",
      fields: [
        { name: "alt", title: "Alt Text", type: "string", description: "Describe the image for accessibility and SEO." },
      ],
      hidden: ({ parent }: any) => parent?.heroDisplay === "3d",
    }),
    defineField({
      name: "heroRightVideo",
      title: "Hero Video",
      type: "object",
      fieldset: "visual",
      description: "Shown when 'Video' is selected above. Upload a file or paste a YouTube/Vimeo URL.",
      hidden: ({ parent }: any) => parent?.heroDisplay !== "video",
      fields: [
        {
          name: "videoFile",
          title: "Upload Video File (mp4 / webm)",
          type: "file",
          options: { accept: "video/mp4,video/webm" },
          description: "Recommended: short looping clip, under 10MB.",
        },
        {
          name: "embedUrl",
          title: "Or paste a YouTube / Vimeo URL",
          type: "url",
          description: "e.g., https://www.youtube.com/watch?v=...",
        },
        {
          name: "autoplay",
          title: "Autoplay & loop",
          type: "boolean",
          initialValue: true,
          description: "Starts playing automatically (muted). Recommended for background videos.",
        },
        {
          name: "posterImage",
          title: "Fallback image",
          type: "image",
          options: { hotspot: true },
          description: "Shown while the video loads, or on devices where autoplay is blocked.",
        },
      ],
    }),
    defineField({
      name: "hero3dModel",
      title: "3D Character Settings",
      type: "object",
      fieldset: "visual",
      description: "Shown when '3D Character' is selected above. Upload your GLB model and tune the camera.",
      hidden: ({ parent }: any) => parent?.heroDisplay !== "3d",
      fields: [
        {
          name: "modelFile",
          title: "3D Model File (.glb)",
          type: "file",
          options: { accept: ".glb,.gltf" },
          description: "Export from Maya/Blender as GLB with the idle animation baked in.",
        },
        {
          name: "headBoneName",
          title: "Head Bone Name",
          type: "string",
          initialValue: "Head",
          description: "The exact bone name in your rig that controls the head (check your Maya outliner). e.g., 'Head', 'Rig_head_jnt'.",
        },
        {
          name: "cameraDistance",
          title: "Camera Distance (zoom)",
          type: "number",
          initialValue: 4.5,
          description: "How far the camera sits from the model. Smaller = closer. Range: 2–8. Default: 4.5.",
        },
        {
          name: "cameraHeight",
          title: "Camera Height",
          type: "number",
          initialValue: 1.0,
          description: "Vertical camera position. 1.0 = mid-body (default). 0.5 = lower. 1.5 = face framing. Range: 0.5–2.0.",
        },
        {
          name: "modelScale",
          title: "Model Scale",
          type: "number",
          initialValue: 1.0,
          description: "Size multiplier. 1.0 = auto-fit. 1.5 = 50% bigger. 0.5 = half size.",
        },
        {
          name: "modelRotationY",
          title: "Model Rotation (degrees)",
          type: "number",
          initialValue: 0,
          description: "Rotate the model left/right. 0 = facing you, 90 = facing left, -90 = facing right, 180 = facing away.",
        },
        {
          name: "headTrackIntensity",
          title: "Head Tracking Intensity",
          type: "number",
          initialValue: 0.6,
          description: "How much the head follows the visitor's cursor. 0 = none, 1 = maximum. Default: 0.6.",
        },
      ],
    }),
    defineField({
      name: "heroVideo",
      title: "Showreel Video",
      type: "object",
      fieldset: "visual",
      description: "The video that plays when visitors click the play badge. Upload a file or paste a YouTube/Vimeo URL.",
      fields: [
        {
          name: "videoFile",
          title: "Upload video file",
          type: "file",
          options: { accept: "video/mp4,video/webm" },
        },
        {
          name: "embedUrl",
          title: "Or paste a YouTube / Vimeo URL",
          type: "url",
          description: "e.g., https://youtu.be/...",
        },
      ],
    }),
    defineField({
      name: "secondaryThumbnail",
      title: "Secondary Thumbnail",
      type: "image",
      fieldset: "visual",
      description: "Small preview image shown in the bottom-right corner of the hero.",
      options: { hotspot: true },
    }),
    defineField({
      name: "showPlayBadge",
      title: "Show the 'Click to Play' badge",
      type: "boolean",
      fieldset: "visual",
      initialValue: true,
      description: "The rotating circular badge on the hero image. Turn off if you have no showreel video.",
    }),
    defineField({
      name: "autoplayVideo",
      title: "Autoplay showreel on load",
      type: "boolean",
      fieldset: "visual",
      initialValue: false,
      description: "Starts the showreel video automatically when the page loads (muted). If off, visitors click the badge to play.",
    }),

    // ── Background & Particles ────────────────────────────────────
    defineField({
      name: "heroBackground",
      title: "Background Style",
      type: "object",
      fieldset: "background",
      description: "The colour or gradient behind the hero content.",
      fields: [
        {
          name: "preset",
          title: "Background",
          type: "string",
          options: {
            list: [
              { title: "Dark (default)", value: "dark" },
              { title: "Midnight — deep blue-black", value: "midnight" },
              { title: "Sunset — dark cinematic red", value: "sunset" },
              { title: "Aurora — deep teal-black", value: "aurora" },
              { title: "Gradient — Lime", value: "gradient-lime" },
              { title: "Gradient — Purple", value: "gradient-purple" },
              { title: "Gradient — Warm amber", value: "gradient-warm" },
              { title: "Gradient — Cool blue", value: "gradient-cool" },
              { title: "Gradient — Custom colours", value: "gradient-custom" },
            ],
            layout: "radio",
          },
          initialValue: "dark",
        },
        {
          name: "color1",
          title: "Custom Colour 1 (start)",
          type: "color",
          description: "Only used when 'Custom colours' is selected.",
          hidden: ({ parent }: any) => parent?.preset !== "gradient-custom",
        },
        {
          name: "color2",
          title: "Custom Colour 2 (end)",
          type: "color",
          description: "Only used when 'Custom colours' is selected.",
          hidden: ({ parent }: any) => parent?.preset !== "gradient-custom",
        },
      ],
    }),
    defineField({
      name: "heroParticles",
      title: "Particles",
      type: "object",
      fieldset: "background",
      description: "Decorative animated particles overlaid on the background.",
      fields: [
        {
          name: "preset",
          title: "Particle Style",
          type: "string",
          options: {
            list: [
              { title: "Dots (default)", value: "dots" },
              { title: "Stars — twinkling field", value: "stars" },
              { title: "Sparks — motion streaks", value: "sparks" },
              { title: "Constellation — connected dots", value: "constellation" },
              { title: "Ribbons — flowing light beams", value: "ribbons" },
              { title: "Orbs — aurora blobs", value: "orbs" },
              { title: "Dust — fine upward particles", value: "dust" },
              { title: "Grid — dot matrix", value: "grid" },
              { title: "None", value: "none" },
            ],
            layout: "radio",
          },
          initialValue: "dots",
        },
        {
          name: "color",
          title: "Particle Colour",
          type: "color",
          description: "Leave blank to use the site accent colour.",
        },
        {
          name: "density",
          title: "Density",
          type: "string",
          options: {
            list: [
              { title: "Low", value: "low" },
              { title: "Medium (default)", value: "medium" },
              { title: "High", value: "high" },
            ],
            layout: "radio",
          },
          initialValue: "medium",
        },
        {
          name: "speed",
          title: "Speed",
          type: "string",
          options: {
            list: [
              { title: "Slow", value: "slow" },
              { title: "Normal (default)", value: "normal" },
              { title: "Fast", value: "fast" },
            ],
            layout: "radio",
          },
          initialValue: "normal",
        },
        {
          name: "opacity",
          title: "Opacity (0 – 1)",
          type: "number",
          initialValue: 0.35,
          description: "0 = invisible, 1 = fully opaque. Default: 0.35.",
          validation: (Rule: any) => Rule.min(0).max(1),
        },
      ],
    }),

    // ── Call to Action ────────────────────────────────────────────
    defineField({
      name: "ctaLabel",
      title: "Button Label",
      type: "string",
      fieldset: "cta",
      initialValue: "SEND ME AN EMAIL",
      description: "The text shown on the button, e.g., 'Send me an email' or 'View my work'.",
    }),
    defineField({
      name: "ctaLink",
      title: "Button Link",
      type: "string",
      fieldset: "cta",
      initialValue: "mailto:hello@noaplinke.com",
      description: "Use mailto:your@email.com for email, or paste any URL.",
    }),
  ],
  preview: {
    select: { title: "heading" },
    prepare({ title }) {
      return { title: title || "Hero Banner", subtitle: "🎬 Hero Section" };
    },
  },
});
