import { defineType, defineField } from "sanity";

export default defineType({
  name: "heroBanner",
  title: "Hero Banner",
  type: "object",
  icon: () => "🎬",
  fields: [
    defineField({
      name: "heading",
      title: "Heading",
      type: "string",
      initialValue: "Animation that hits different",
      validation: (Rule) => Rule.required().error("Please add a heading for your hero section"),
    }),
    defineField({
      name: "subtitle",
      title: "Subtitle",
      type: "text",
      rows: 3,
    }),
    defineField({
      name: "heroImage",
      title: "Hero Image",
      type: "image",
      options: { hotspot: true },
      fields: [
        { name: "alt", title: "Alt Text", type: "string" },
      ],
      hidden: ({ parent }: any) => parent?.heroDisplay === "3d",
    }),
    defineField({
      name: "heroDisplay",
      title: "Hero Display Mode",
      type: "string",
      description: "Choose what appears on the right side of the hero",
      options: {
        list: [
          { title: "Image", value: "image" },
          { title: "Video (looping background)", value: "video" },
          { title: "3D Character (interactive)", value: "3d" },
        ],
        layout: "radio",
      },
      initialValue: "image",
    }),
    defineField({
      name: "heroRightVideo",
      title: "Hero Right Video",
      type: "object",
      description: "Video shown as the main hero visual on the right side",
      hidden: ({ parent }: any) => parent?.heroDisplay !== "video",
      fields: [
        {
          name: "videoFile",
          title: "Upload Video File (mp4 / webm)",
          type: "file",
          options: { accept: "video/mp4,video/webm" },
          description: "Recommended: short looping clip, ideally muted",
        },
        {
          name: "embedUrl",
          title: "Or Paste YouTube / Vimeo URL",
          type: "url",
          description: "Paste a YouTube or Vimeo URL to embed it",
        },
        {
          name: "autoplay",
          title: "Autoplay & Loop",
          type: "boolean",
          initialValue: true,
          description: "Automatically play and loop the video (muted). Recommended for background videos.",
        },
        {
          name: "posterImage",
          title: "Poster / Fallback Image",
          type: "image",
          options: { hotspot: true },
          description: "Shown while the video loads or on devices where autoplay is blocked",
        },
      ],
    }),
    defineField({
      name: "hero3dModel",
      title: "3D Model Settings",
      type: "object",
      description: "Upload your character model and configure the head tracking",
      hidden: ({ parent }: any) => parent?.heroDisplay !== "3d",
      fields: [
        {
          name: "modelFile",
          title: "3D Model File (.glb)",
          type: "file",
          options: { accept: ".glb,.gltf" },
          description: "Export from Maya/Blender as GLB with the idle animation baked in",
        },
        {
          name: "headBoneName",
          title: "Head Bone Name",
          type: "string",
          initialValue: "Head",
          description: "The exact name of the head bone in your rig (e.g., 'Head', 'head_jnt', 'mixamorig:Head'). Check your Maya outliner.",
        },
        {
          name: "cameraDistance",
          title: "Camera Distance",
          type: "number",
          initialValue: 4.5,
          description: "How far the camera is from the character. Smaller = closer. Default: 4.5",
        },
        {
          name: "cameraHeight",
          title: "Camera Height",
          type: "number",
          initialValue: 1.0,
          description: "Vertical position of the camera. Default: 1.0",
        },
        {
          name: "modelScale",
          title: "Model Scale",
          type: "number",
          initialValue: 1.0,
          description: "Scale of the 3D model. Increase if it's too small. Default: 1.0",
        },
        {
          name: "headTrackIntensity",
          title: "Head Track Intensity",
          type: "number",
          initialValue: 0.6,
          description: "How much the head follows the cursor (0 = none, 1 = full). Default: 0.6",
        },
      ],
    }),
    defineField({
      name: "heroVideo",
      title: "Hero Video (optional)",
      type: "object",
      description: "Upload a video or paste a URL — shows on click of the play badge",
      fields: [
        { name: "videoFile", title: "Upload Video File", type: "file",
          options: { accept: "video/mp4,video/webm" } },
        { name: "embedUrl", title: "Or Paste YouTube/Vimeo URL", type: "url" },
      ],
    }),
    defineField({
      name: "secondaryThumbnail",
      title: "Secondary Thumbnail",
      type: "image",
      description: "Small image shown in the bottom-right of the hero",
      options: { hotspot: true },
    }),
    defineField({
      name: "showPlayBadge",
      title: "Show Play Badge",
      type: "boolean",
      initialValue: true,
      description: 'The rotating "CLICK TO PLAY" circle on the hero image',
    }),
    defineField({
      name: "autoplayVideo",
      title: "Autoplay Video",
      type: "boolean",
      initialValue: false,
      description: "Automatically start playing the video when the page loads (muted). If off, visitors click the play badge to start.",
    }),
    defineField({
      name: "tags",
      title: "Specialty Tags",
      type: "array",
      of: [{ type: "string" }],
      description: "The scattered pill tags (e.g., Gameplay Animation, Rigging)",
      initialValue: [
        "Gameplay Animation",
        "Game Development",
        "Engine Implementation",
        "Workflow Optimization",
        "Rigging",
        "Procedural Animations",
      ],
    }),
    defineField({
      name: "heroBackground",
      title: "Background",
      type: "object",
      description: "Controls the colour/gradient behind the hero content",
      fields: [
        {
          name: "preset",
          title: "Background Style",
          type: "string",
          options: {
            list: [
              { title: "Dark (default)", value: "dark" },
              { title: "Gradient — Lime", value: "gradient-lime" },
              { title: "Gradient — Purple", value: "gradient-purple" },
              { title: "Gradient — Warm amber", value: "gradient-warm" },
              { title: "Gradient — Cool blue", value: "gradient-cool" },
              { title: "Gradient — Custom colours", value: "gradient-custom" },
            ],
            layout: "radio",
          },
          initialValue: "dark",
        },
        {
          name: "color1",
          title: "Custom Colour 1 (start)",
          type: "color",
          description: "Only used when 'Custom colours' is selected above",
          hidden: ({ parent }: any) => parent?.preset !== "gradient-custom",
        },
        {
          name: "color2",
          title: "Custom Colour 2 (end)",
          type: "color",
          description: "Only used when 'Custom colours' is selected above",
          hidden: ({ parent }: any) => parent?.preset !== "gradient-custom",
        },
      ],
    }),
    defineField({
      name: "heroParticles",
      title: "Particles",
      type: "object",
      description: "Decorative floating particles overlaid on the background",
      fields: [
        {
          name: "preset",
          title: "Particle Style",
          type: "string",
          options: {
            list: [
              { title: "Dots (default)", value: "dots" },
              { title: "Stars (twinkling)", value: "stars" },
              { title: "Sparks (streaks)", value: "sparks" },
              { title: "Constellation (connected dots)", value: "constellation" },
              { title: "None", value: "none" },
            ],
            layout: "radio",
          },
          initialValue: "dots",
        },
        {
          name: "color",
          title: "Particle Colour",
          type: "color",
          description: "Leave blank to use the site accent colour (#c9fb00)",
        },
        {
          name: "density",
          title: "Density",
          type: "string",
          options: {
            list: [
              { title: "Low — 22 particles", value: "low" },
              { title: "Medium — 44 particles (default)", value: "medium" },
              { title: "High — 72 particles", value: "high" },
            ],
            layout: "radio",
          },
          initialValue: "medium",
        },
        {
          name: "speed",
          title: "Speed",
          type: "string",
          options: {
            list: [
              { title: "Slow", value: "slow" },
              { title: "Normal (default)", value: "normal" },
              { title: "Fast", value: "fast" },
            ],
            layout: "radio",
          },
          initialValue: "normal",
        },
        {
          name: "opacity",
          title: "Opacity (0 – 1)",
          type: "number",
          initialValue: 0.35,
          description: "0 = invisible, 1 = fully opaque. Default: 0.35",
          validation: (Rule: any) => Rule.min(0).max(1),
        },
      ],
    }),
    defineField({
      name: "ctaLabel",
      title: "CTA Button Label",
      type: "string",
      initialValue: "SEND ME AN EMAIL",
    }),
    defineField({
      name: "ctaLink",
      title: "CTA Button Link",
      type: "string",
      initialValue: "mailto:hello@noaplinke.com",
      description: "Use mailto:your@email.com for email, or a URL",
    }),
  ],
  preview: {
    select: { title: "heading" },
    prepare({ title }) {
      return { title: title || "Hero Banner", subtitle: "🎬 Hero Section" };
    },
  },
});
